---
kind: Service
apiVersion: v1
metadata:
  name: python-app-4863
  namespace: app
spec:
  type: LoadBalancer
  selector:
    app: app-HgPej81a
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 5000
      nodePort: 30000
      name: ui