---
kind: Service
apiVersion: v1
metadata:
  name: python-app-{name}
  namespace: app
spec:
  type: LoadBalancer
  selector:
    app: app-{version}
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 5000
      nodePort: 31010
      name: ui