apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::070814490905:role/aztec-cloudtribe-infraadmin-assumerole
      username: admin
      groups:
        - system:masters
    - rolearn: arn:aws:iam::070814490905:role/eks-node-group-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
